# Netlify 설정 파일

# 루트 경로 리디렉션 규칙 제거됨 (index.html이 기본 파일)

# API 프록시 규칙
[[redirects]]
  from = "/explorer-api/*"
  to = "http://itsmyzone.iptime.org/explorer-api/:splat"
  status = 200
  # force = true # API 프록시는 항상 우선 적용하는 것이 좋을 수 있음
